name: Add Reviewers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: AlexBaranowski,septymka,micnee,visse0001
        re-request-when-approved: true
        re-request-when-changes-requested: true
