name: flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
